matrix:
  include:
    - language: python
      python:
        - 3.6
        - 3.7
        - 3.8
      stage: python
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: rust
      rust:
        - stable
      stage: rust

stages:
  - rust
  - python
  - test

install:
  - pip install -r requirements.txt
  - build/get_latex_snippet
# before_script:
#   - mysql -e 'create database test;' -u root
# command to run tests
script:
  - python3 manage.py test
