language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --profile=minimal -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - which cargo
  - echo $PATH
# command to install dependencies
# env:
#  -DJANGO=2.2 DB=mysql
install:
  - which cargo
  - build/create_venv
  - echo $PATH
  - source venv/bin/activate
  - export PATH=$HOME/.cargo/bin:$PATH
  - python --version
  - echo $PATH
  - which cargo
  - build/get_latex_snippet
# before_script:
#   - mysql -e 'create database test;' -u root
# command to run tests
script:
  - python manage.py test
