language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

# language: python
# python:
#   - "3.6"      # current default Python on Travis CI
#   - "3.7"
#   - "3.8"

# command to install dependencies
# env:
#  -DJANGO=2.2 DB=mysql
install:
  - pip install -r requirements.txt
  - build/get_latex_snippet
# before_script:
#   - mysql -e 'create database test;' -u root
# command to run tests
script:
  - python3 manage.py test
