language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --profile=minimal -y
# command to install dependencies
# env:
#  -DJANGO=2.2 DB=mysql
install:
  - which pip
  - pip --version
  - python --version
  - pip install -r requirements.txt
  - build/get_latex_snippet
# before_script:
#   - mysql -e 'create database test;' -u root
# command to run tests
script:
  - python manage.py test
