# Generated by Django 2.2.3 on 2020-02-21 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMediaAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_position', models.PositiveIntegerField(blank=True, null=True)),
                ('media_title', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.PageMedia')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Pages')),
            ],
        ),
        migrations.AddField(
            model_name='pages',
            name='media',
            field=models.ManyToManyField(related_name='pagemedias', through='admin_app.PageMediaAssociation', to='admin_app.PageMedia'),
        ),
    ]
