# Generated by Django 2.2.3 on 2020-03-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='whitepaper_category',
            field=models.CharField(blank=True, help_text='If this page is meant to be a whitepaper, please select a category. The category list is maintained by system administrators and can not be dynamic.', max_length=255, null=True),
        ),
    ]
