# Generated by Django 2.2.3 on 2020-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20200221_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='publication',
            field=models.BooleanField(default=False, help_text='Problem is ready for public viewing', verbose_name='Publish Problem'),
        ),
    ]
