# Generated by Django 2.2.3 on 2020-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_problemset_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='whitepaper',
            field=models.BooleanField(default=False, help_text='Is this a whitepaper?', verbose_name='Whitepaper'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='publication',
            field=models.BooleanField(default=False, help_text='Problem Set is ready for public viewing', verbose_name='Publish Problem Set'),
        ),
    ]
