# Generated by Django 2.2.3 on 2020-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_pages_whitepaper_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='publication',
            field=models.BooleanField(default=False, help_text='Page or Whitepaper is ready for public viewing.', verbose_name='Publish Page or Whitepaper'),
        ),
    ]
