# Generated by Django 2.2.3 on 2020-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20200321_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problemset',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequenceitems',
            name='required',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
