# Generated by Django 2.2.3 on 2020-03-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20200323_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemsetitems',
            options={'ordering': ['item_position']},
        ),
        migrations.AlterField(
            model_name='problemsetitems',
            name='problem_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_problems', to='admin_app.ProblemSet'),
        ),
        migrations.CreateModel(
            name='ProblemSetPDFs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='problem_set_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_set_pdfs', to='admin_app.ProblemSet')),
            ],
        ),
    ]
