# Generated by Django 2.2.13 on 2020-08-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereq',
            field=models.TextField(blank=True, null=True, verbose_name='Prerequisites'),
        ),
    ]
