# Generated by Django 2.2.13 on 2020-08-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_courseday_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseday',
            name='number',
        ),
        migrations.AddField(
            model_name='courseday',
            name='order',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courseday',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseday',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
