# Generated by Django 2.2.13 on 2020-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_auto_20200814_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseday',
            name='resources',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='courseday',
            name='topic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
