# Generated by Django 2.2.13 on 2020-08-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_auto_20200814_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=8)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='admin_app.CourseDay')),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_due', to='admin_app.CourseDay')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=8)),
                ('show_handout', models.BooleanField(default=False, help_text='Show handout to students.')),
                ('show_solution', models.BooleanField(default=False, help_text='Show solution to students.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.CourseDay')),
            ],
        ),
        migrations.AddField(
            model_name='courseday',
            name='activities',
            field=models.ManyToManyField(related_name='day', through='admin_app.DayActivity', to='admin_app.Activity'),
        ),
        migrations.AddField(
            model_name='courseday',
            name='problems',
            field=models.ManyToManyField(related_name='day', through='admin_app.DayProblem', to='admin_app.Problem'),
        ),
        migrations.AddField(
            model_name='courseday',
            name='problemset',
            field=models.ManyToManyField(related_name='due', through='admin_app.DayProblem', to='admin_app.Problem'),
        ),
    ]
