# Generated by Django 2.2.13 on 2020-08-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_auto_20200817_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='course_learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='learning_progression_concepts',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='program_learning_outcomes',
        ),
    ]
