# Generated by Django 2.2.3 on 2020-03-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_pages_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='items',
            field=models.ManyToManyField(through='admin_app.ProblemSetItems', to='admin_app.Problem'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='publication',
            field=models.BooleanField(default=False, help_text='Whitepaper is ready for public viewing.', verbose_name='Publish Whitepaper'),
        ),
    ]
