# Generated by Django 2.2.3 on 2020-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_auto_20200324_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsetpdfs',
            name='solution',
            field=models.BooleanField(default=False, help_text='Does this include the solution?', verbose_name='Solution Included'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='publication',
            field=models.BooleanField(default=False, help_text='Problem Set is ready for public viewing. Takes 5-10 seconds to generate new problem set PDFs', verbose_name='Publish Problem Set'),
        ),
    ]
