# Generated by Django 2.2.3 on 2020-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20200324_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsetitems',
            name='required',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
