# Generated by Django 2.2.3 on 2020-03-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_problemsetitems_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['problem_title'], 'permissions': (('can_edit_problem', 'Edit Problem'), ('can_add_problem', 'Add Problem'), ('can_view_solution', 'View Solution'))},
        ),
    ]
