# Generated by Django 2.2.13 on 2020-08-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_course_prereq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('outcome', models.CharField(blank=True, help_text='A human-friendly short name of course', max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Course')),
            ],
        ),
    ]
