# Generated by Django 2.2.13 on 2020-08-12 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_courselearningoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(blank=True, help_text='include ph e.g. "ph425"', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a value of form ph123', regex='^ph\\d+$')]),
        ),
        migrations.CreateModel(
            name='CourseAsTaught',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Course')),
            ],
        ),
    ]
