# Generated by Django 2.2.13 on 2020-08-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_auto_20200816_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayproblem',
            name='instructions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dayproblem',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayproblem', to='admin_app.CourseDay'),
        ),
    ]
