# Generated by Django 2.2.13 on 2020-08-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_auto_20200816_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseday',
            name='problemsetname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
