# Generated by Django 2.2.13 on 2020-08-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_courseday_problemsetname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayactivity',
            options={'ordering': ['day__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='dayproblem',
            options={'ordering': ['due__order', 'order']},
        ),
    ]
