# Generated by Django 2.2.13 on 2020-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_activity_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='learning_outcomes',
            field=models.ManyToManyField(related_name='problems', to='admin_app.CourseLearningOutcome'),
        ),
    ]
