# Generated by Django 2.2.13 on 2020-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_problem_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseday',
            name='show_solution',
            field=models.BooleanField(default=False, help_text='Show problem set solution to students.'),
        ),
    ]
