# Generated by Django 2.2.13 on 2020-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_courseastaught_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseastaught',
            name='office_hours',
            field=models.TextField(blank=True),
        ),
    ]
