# Generated by Django 2.2.13 on 2020-09-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseastaught',
            name='modification_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
