# Generated by Django 2.2.13 on 2020-09-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_courseastaught_modification_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseday',
            name='show_problemset',
            field=models.BooleanField(default=False, help_text='Show problem set to students.'),
        ),
    ]
