# Generated by Django 2.2.13 on 2020-09-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_courseday_show_problemset'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='readings',
            field=models.TextField(blank=True),
        ),
    ]
