# Generated by Django 2.2.13 on 2020-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0036_activity_readings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_resources',
            field=models.TextField(blank=True, verbose_name='Syllabus learning resources'),
        ),
    ]
