# Generated by Django 2.2.13 on 2020-10-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0037_course_learning_resources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': (('can_edit_activity', 'Edit Activity'), ('can_add_activity', 'Add Activity'), ('can_view_solution', 'View Solution')), 'verbose_name_plural': 'activities'},
        ),
    ]
