# Generated by Django 2.2.13 on 2020-10-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_auto_20201002_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseastaught',
            name='today',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.CourseDay'),
        ),
    ]
