# Generated by Django 2.2.13 on 2020-10-22 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0039_courseastaught_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(default='ph000', help_text='include ph e.g. "ph425"', max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a value of form ph123', regex='^(ph|aims|mth)\\d+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='quarter_numbers',
            field=models.CharField(default='1', help_text='e.g. Fall of Junior year = 7, comma delimit if taught at multiple stages', max_length=255),
        ),
    ]
