# Generated by Django 2.2.13 on 2020-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_auto_20201102_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseastaught',
            name='available',
            field=models.BooleanField(default=False, help_text='Show course to students.'),
        ),
    ]
