# Generated by Django 2.2.13 on 2020-12-28 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0044_courseastaught_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(help_text='include ph e.g. "ph425"', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a value of form ph123', regex='^(ph|aims|mth)\\d+$')]),
        ),
    ]
