# Generated by Django 2.2.13 on 2021-01-24 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0045_auto_20201227_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseastaught',
            name='today',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.CourseDay'),
        ),
    ]
